title: HidyBot Documentation
description: HidyBot Documentation
theme: just-the-docs

url: https://b3h1z.github.io/HidyBot-Docs

aux_links:
  Template Repository: https://github.com/B3H1Z/HidyBot-Docs

nav_enabled: false